Workiva/w_flux

- .gitignore
- .travis.yml
- pubspec.yaml
- smithy.yml
#27 Travis CI
#28 Codecov.io
Dart 1.12 introduces a new `.packages` file that should be ignored
- Updated dart_dev dep to use the pub version
- Removed `smithy.yml`
- Submitted ticket to have smithy turned off for this repo: https://jira.atl.workiva.net/secure/Dashboard.jspa
- Added `travis.yml` to run..
- static analysis
- dart formatter check
- tests
- coverage
- coverage reporting
- Added `.packages` to gitignore
- CI builds
- Travis CI passes
- Coverage is reported to codecov.io and codecov.io checks pass
- Ignore failing smithy checks
@jayudey-wf
> CP-937 Setup Travis CI and codecov.io reporting, w_flux

- README.md
- example/README.md
- #32 
- Missing a "development" section in the readme
- Update example readme to use a `dart_dev` command to serve examples
- Update main readme to include a "development" section that references dart_dev
> **Docs only change.**
- Instructions for serving examples
- Following instructions in /example/README.md should successfully serve the examples
@jayudey-wf
> CP-940 Update readmes to use/reference dart_dev, w_flux

- test/action_test.dart
`expectAsync` is being used incorrectly in our action tests. The current usage correctly catches incorrect payloads, but does not fail when the actions are not called.
**Tests:**
- Updated `expectAsync` usage to wrap the `action.listen` callback.
- n/a
- CI Passes.
- Commenting out lines 37, 45, and 53 in `test/action_test.dart` should cause those respective tests to timeout
@jayudey-wf
> CP-1017 Fix usage of expect-async in action tests.

- pubspec.yaml
Fixes #39 
**Source:**
- Update `react` dependency range to include 0.8.x
- None
- CI passes
> CP-1055 Allow react 0.8.0 in dependency range, w_flux

- lib/src/action.dart
- test/action_test.dart
It would be nice to be able to have a way to easily cancel all Action subscriptions in the teardown of a unit test or some module.
This PR allows consumers to clear all listeners of an Action with a new `clearListeners` method.
**Source:**
- Add `clearListeners` method to `Action`.
**Tests:**
- Add unit test to ensure `.clearListeners()` works as expected
- None. New functionality only.
- CI passes
- Unit test properly covers new functionality
> CP-1152 Add clearListeners method to Action

- lib/src/action.dart
- lib/src/component.dart
- lib/src/store.dart
- test/action_test.dart
- test/store_test.dart
- ran `dartanalyzer --strong lib/w_flux.dart` and fixed the output results:
```
Analyzing [lib/w_flux.dart]...
[error] Type check failed: [store] (List<dynamic>) is not of type List<Store> because store cannot be typed as Store (/Volumes/CASE/code/w_flux/lib/src/component.dart, line 95, col 14)
[warning] Missing concrete implementation of 'Function.==' (/Volumes/CASE/code/w_flux/lib/src/action.dart, line 44, col 7)
[warning] this.props['actions'] (dynamic) will need runtime check to cast to type ActionsT (/Volumes/CASE/code/w_flux/lib/src/component.dart, line 33, col 27)
[warning] this.props['store'] (dynamic) will need runtime check to cast to type StoresT (/Volumes/CASE/code/w_flux/lib/src/component.dart, line 51, col 24)
[warning] new Map.fromIterable(redrawOn(), value: (_) => (_) => …
```
> CP-1168 fix strong mode analysis errors / warnings, w_flux

- .travis.yml
- lib/src/component.dart
- lib/src/mixins/batched_redraws.dart
- lib/w_flux.dart
- test/action_test.dart
- test/component_test.dart
- test/mixins/batched_redraws_test.dart
- test/store_test.dart
- tool/dev.dart
`FluxComponent` instances aren't very smart about how they redraw and will happily attempt to redraw multiple times per animation frame. This results in some pretty dramatic performance problems and forces manual tuning.
We have seen some nice performance improvements by making them a little smarter and we thought this would make a nice addition to w_flux itself. Basically, we override the `redraw()` method and batch redraws across all components.
The first time a component asks for a redraw a countdown is started, subsequent redraw requests from that component will be ignored. Requests from other components between the time the countdown is started and the time the countdown expires (on the next animation frame) will be added and handled when the countdown expires. We then call …
> REF-278 Add batched redraws and basic tests.

- README.md
- lib/src/store.dart
- test/store_test.dart
- #48 Because the only constructor in `Store` has optional parameters, extending classes cannot mix other classes in.
**Source:**
- Fix #48 by removing the optional `transformer` parameter from the default `Store` constructor and replacing it with a named `Store.withTransformer()` constructor. **This is a breaking change.**
**Tests:**
- Update test for transformer usage.
- Store streams (transformed or not).
- CI passes.
@jayudey-wf
> CP-1192 Store: switch to a default ctor and a transformer ctor

- CHANGELOG.md
- example/random_color/index.html
- example/todo_app/index.html
- pubspec.yaml
- test/action_test.dart
- test/component_test.dart
- test/store_test.dart
- test/utils.dart
react-dart 0.9.0 is available.
**Source:**
- Update react dependency range.
**Tests:**
- Fix tests that are currently broken in master.
- Examples
- CI passes
- Examples function correctly
FYI @aaronlademann-wf
> CP-1415 Allow use of react-dart 0.9.0, w_flux

- pubspec.yaml
react-dart 1.0.0 was just released, and it is still compatible with the current version w_flux.
The `react` version range has been updated to include 1.x.x versions.
@trentgrover-wf @maxwellpeterson-wf @evanweible-wf
> CP-1598 Widen react-dart version range to support 1.0.0, w_flux

- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-1432
Releases that need to go out at the same time (if any): 
CP-1598  - Widen react-dart version range to support 1.0.0, w_flux  - https://github.com/Workiva/w_flux/pull/56
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.1.0...CP-1432_release_2.2.0
> CP-1432 Release w_flux 2.2.0

- lib/src/component_client.dart
- lib/src/component_common.dart
- lib/src/component_server.dart
- lib/w_flux_server.dart
- test/component_server_test.dart
Fixes #55.
**Source:**
- Extract functionality of current `FluxComponent` into a new shared `FluxComponentCommon` class.
- Create new `FluxComponent` class that utilizes the `BatchedRedrawMixin` for use on the client.
- Create new `FluxComponent` class that does not utilize the mixin for use on the server.
- Add new entry point for `w_flux_server.dart`.
**Tests:**
- Duplicated all component tests to test against the new `w_flux_server.dart` entrypoint in the VM only.
- CI passes.
- Can import `package:w_flux/w_flux_server.dart` without throwing an error about importing `dart:html`.
@timmccall-wf 
@todbachman-wf 
@georgelesica-wf 
@aaronstgeorge-wf 
@bencampbell-wf
> CP-1736 New entry point for use on the server

- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-1600
Releases that need to go out at the same time (if any): 
CP-1736  - New entry point for use on the server  - https://github.com/Workiva/w_flux/pull/58
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.2.0...CP-1600_release_2.3.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.2.0...2.3.0
> CP-1600 Release w_flux 2.3.0

- example/random_color/random_color.dart
- example/todo_app/todo_app.dart
- pubspec.yaml
react-dart 2.0.0 was just released, and it is still compatible with the current version w_flux.
The react version range has been updated to include 2.x.x versions.
Do not use removed API in examples.
@trentgrover-wf @maxwellpeterson-wf @evanweible-wf
> CP-1931 Widen react-dart version range to support 2.0.0

- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-1753
Releases that need to go out at the same time (if any): 
======= w_flux 2.3.1 items =======
CP-1931  - Widen react-dart version range to support 2.0.0  - https://github.com/Workiva/w_flux/pull/60
======= end =======
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.3.0...CP-1753_release_2.3.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.3.0...2.3.1
> CP-1753 Release w_flux 2.3.1

- lib/src/mixins/batched_redraws.dart
- pubspec.yaml
- test/component_server_test.dart
- test/component_test.dart
- test/mixins/batched_redraws_test.dart
- test/store_test.dart
react-dart 3.0.0 was just released, it includes the addition of setState/redraw callbacks.
`BatchedRedrawMixin` and `_RedrawScheduler ` needed to be updated to support this.
Now `_RedrawScheduler` chains all callbacks passed to `redraw` and passes the chained function to `setState`.
This will need to be a major release due to the API in `BatchedRedrawMixin` updating.
@trentgrover-wf @maxwellpeterson-wf @evanweible-wf @greglittlefield-wf @georgelesica-wf
> CP-2381 Bump react-dart version constraint to ^3.0.0

- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-2036
Releases that need to go out at the same time (if any): 
======= w_flux 2.4.0 items =======
CP-2381  - Bump react-dart version constraint to ^3.0.0  - https://github.com/Workiva/w_flux/pull/65
======= end =======
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.3.1...CP-2036_release_2.4.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.3.1...2.4.0
> CP-2036 Release w_flux 2.4.0

- lib/src/component_client.dart
- lib/src/mixins/batched_redraws.dart
- test/component_test.dart
- test/mixins/batched_redraws_test.dart
- Continuation of https://github.com/Workiva/w_flux/pull/68
- In some cases, components that use BatchedRedraws to delay rendering to the next animation frame could attempt to render components that are no longer mounted to the DOM (this causes a react setState console error).
- add a `shouldBatchRedraw` bool to the BatchedRender mixin that can be set to false to short circuit the delayed render
- set `shouldBatchRedraw` to false when unmounting FluxComponent
NOTE: need to submit a follow up PR to web_skin_dart to add the unmounting logic to `FluxUiComponent` so that this can fix https://github.com/Workiva/wdesk_examples/issues/72 (and likely other misc things)
- CI passes (new unit tests added)
@jayudey-wf 
@sebastianmalysa-wf …
> CHART-1761 add shouldRedraw check on BatchedRedraws

- pubspec.yaml
* [CHART-1760 make w_flux compatible with strong mode](https://github.com/Workiva/w_flux/pull/67)
* [CHART-1761 add shouldRedraw check on BatchedRedraws](https://github.com/Workiva/w_flux/pull/70)
Requested by: charliekump-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.4.0...version-bump-w_flux-2-5-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.4.0...2.5.0
> CP-2399 Release w_flux 2.5.0

- .travis.yml
- pubspec.yaml
- smithy.yaml
- test/component_test.dart
- tool/dev.dart
- Fix intermittent component test failures by awaiting `window.animationFrame`s instead of hardcoded awaits
- Add a basic smithy.yaml (cherry-picked @jayudey-wf's commit) for dependency tracking
- Add a sleep to Travis CI startup after starting xvfb to prevent content-shell failures
- Upgrade dependencies and set `pubServe = true` for coverage task for Dart 1.20 compat
@jayudey-wf 
@sebastianmalysa-wf
> CP-2944 Fix intermittent failures, add basic smithy.yaml, add sleep to Travis CI startup

- .travis.yml
- lib/src/action.dart
- lib/src/component_common.dart
- lib/src/constants.dart
- lib/src/store.dart
- pubspec.yaml
- test/action_test.dart
- test/store_test.dart
*Fixes #61, #69, #73*
Store does not clean up its StreamController or its ActionSubscriptions, and provides no way to do so.
Store now extends [w_common's Disposable](https://github.com/Workiva/w_common). The internal StreamController and any ActionSubscriptions are cleaned up on dispose.
Bonus: Store test usage of expectAsync was corrected.
No regressions in Store usage. Full test coverage for the new code was added.
@jayudey-wf 
(did I miss anyone?)
> CP-2596 Store implements Disposable

- .analysis_options
- lib/src/action.dart
If strong mode is enabled on one of your Action handlers is marked as an `async` function, the following analysis error is shown:
`async` functions can be very useful for Action handlers, because you may want to leverage `await`.
**Source:**
* Relax return type of Action handler from `void` to `dynamic`.
- CI Passes
@Workiva/web-platform-pp
@Workiva/rich-app-platform-pp
> Relax Action handler return type

- pubspec.yaml
* [CP-3349 Relax Action handler return type](https://github.com/Workiva/w_flux/pull/80)
Requested by: @evanweible-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.6.0...version-bump-w_flux-2-6-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.6.0...2.6.1
> CP-2958 Release w_flux 2.6.1

- .travis.yml
- lib/src/store.dart
- pubspec.yaml
- smithy.yaml
- test/store_test.dart
Allow more flexible access to a `Store`'s trigger stream, particularly for testing.
Add a `stream` getter to the `Store` class.
**MINOR**. Adds new API to the `Store` class.
- CI passes
> HY-4736 Expose trigger stream on store

- pubspec.yaml
* [WP-3660 : added docs.yml](https://github.com/Workiva/w_flux/pull/82)
* [HY-4736 Expose trigger stream on store](https://github.com/Workiva/w_flux/pull/84)
Requested by: @evanweible-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.6.1...version-bump-w_flux-2-7-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.6.1...2.7.0
> WP-3352 Release w_flux 2.7.0

- lib/src/component_common.dart
- pubspec.yaml
The`dart_style` and `dartdoc` dependency ranges are blocking progress on strong-mode / DDC work.  
Specifically, supporting the `covariant` keyword in over_react props / state classes ([UIP-2024](https://jira.atl.workiva.net/browse/UIP-2024)).
These changes bring the dependency ranges of `dart_style` and `dartdoc` in-line with the ranges found within the current version of `dart_dev`.
---
FYA @Workiva/web-platform-pp 
FYI @Workiva/ui-platform-pp
> WP-4411 Update dependencies

- pubspec.yaml
* [WP-4052 Add a note about over_react's FluxUiComponent](https://github.com/Workiva/w_flux/pull/86)
* [WP-4411 Update dependencies](https://github.com/Workiva/w_flux/pull/88)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.7.0...version-bump-w_flux-2-7-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.7.0...2.7.1
> WP-3983 Release w_flux 2.7.1

- .analysis_options
- test/component_server_test.dart
- test/component_test.dart
The `close_sinks` and `cancel_subscriptions` lints were not enabled. When I enabled them, I found two small places in tests where `StreamController`s were never closed.
- Enable them.
- Close the offending controllers in the tests.
> WP-4432 Add lints and close test controllers.

- lib/src/store.dart
- test/action_test.dart
- test/component_server_test.dart
- test/component_test.dart
- test/store_test.dart
- tool/dev.dart
Problem
--------
Store.trigger() will throw an exception if disposing (but not if fully disposed):
```
Bad state: Cannot add new events after calling close
dart:async                                                            _BroadcastStreamController.add
package:w_flux/src/store.dart 119:23                                  Store.trigger
package:w_flux/src/store.dart 138:7                                   Store.triggerOnAction.<fn>
package:w_flux/src/action.dart 66:65                                  Action.call.<fn>.<fn>
```
Solution
--------
Check `isDisposedOrDisposing` before attempting to add events to the streamController in trigger() 
Potential Regressions
---------------------
This is `trigger()` code, so any time any Store `trigger()`s. But `isDisposedOrDisposing` semantics …
> WP-4459 Ignore trigger when disposed or disposing

- lib/src/component_common.dart
- lib/src/store.dart
- pubspec.yaml
- test/component_server_test.dart
- test/component_test.dart
- test/store_test.dart
Problem
--------
- tests on master were failing
Solution
--------
- rate_limit was still used in a test, so I swapped in rxdart and made it a dev dependency
- on tests that simulated component unmount, await didDispose before continuing
- fixed some deprecation warnings
Potential Regressions
--------
None, the dependency appears unused.
QA / +10
--------
> WP-4872 fix broken tests and deprecations

- lib/src/store.dart
- test/store_test.dart
[Jira Ticket](https://jira.atl.workiva.net/browse/RAP-2146)
We want `Store` to extend `Stream` so that consumers can listen to it as though it was a stream itself.
Extend `Stream` and implement `listen` and `isBroadcast`. I've also deprecated `stream` since it is no longer necessary.
None.
Added and/or updated.
1. CI passes
@regenvanwalbeek-wf @evanweible-wf
> RAP-2146 Make store extend Stream

- pubspec.yaml
* [WP-4449 Remove rate limit dependency.](https://github.com/Workiva/w_flux/pull/91)
* [WP-4872 fix broken tests and deprecations](https://github.com/Workiva/w_flux/pull/94)
* [RAP-2146 Make store extend Stream](https://github.com/Workiva/w_flux/pull/95)
Requested by: @georgelesica-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.7.2...version-bump-w_flux-2-8-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.7.2...2.8.0
> WP-4467 Release w_flux 2.8.0

- lib/src/component_common.dart
This was causing two problems:
1. If store is a mock this fails due to an argument error unless the mock is configured to return a stream for store.stream
2. stream is deprecated and should not be used, plus it is only visible for testing. 
With this, a mocked store now needs to stub listen rather than stream.
> WP-4923 Stop using the deprecated stream

- lib/src/component_client.dart
- lib/src/mixins/batched_redraws.dart
- pubspec.yaml
- test/component_test.dart
- test/component_test.html
- test/mixins/batched_redraws_test.dart
Flux components were rerendered excessively when nested inside each other and a store trigger caused rerendering of those nested components.
See reduced test case [here](https://gist.github.com/greglittlefield-wf/e2cd42b03261e1cb11817a6e5718025d).
Track whether components were already redrawn during the current redraw batch.
All consumers will need to do is make sure to call `super.componentDidUpdate` in overrides, and they'll get this fix.
_OverReact PR (`FluxUiComponent`) is available here: https://github.com/Workiva/over_react/pull/103._
Verify tests pass.
Flux component rerendering
---
FYA @Workiva/web-platform-pp @Workiva/ui-platform-pp 
FYI: @kylemcmorrow-wf @johnbland-wf @brentschuele-wf @brandonrodgers-wf @robbielamb-wf
> WP-4924 Redraw only once when store triggers along with ancestor rerender

- pubspec.yaml
* [WP-4924 Redraw only once when store triggers along with ancestor rerender](https://github.com/Workiva/w_flux/pull/96)
* [WP-4923 Stop using the deprecated stream](https://github.com/Workiva/w_flux/pull/100)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.8.0...version-bump-w_flux-2-9-0_2
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.8.0...2.9.0
> WP-4915 Release w_flux 2.9.0

- lib/src/component_client.dart
- test/component_test.dart
Currently, when a component calls `setState` at the same time the store triggers, the rerender with the updated store does not take place.
Use `componentWillReceiveProps` to mark batch redraws instead of `componentDidUpdate`.
This will mark only components that are getting excessive rerenders from parent components, and not components that have unrelated `setState` calls.
___Also fixed in over_react: https://github.com/Workiva/over_react/pull/108___
- Verify tests pass
FluxUiComponent batch redrawing.
---
FYA: @Workiva/ui-platform-pp @Workiva/web-platform-pp
> WP-4937 Fix case where setState and store trigger only result in one render

- .travis.yml
- pubspec.yaml
* [WP-4937 Fix case where setState and store trigger only result in one render](https://github.com/Workiva/w_flux/pull/105)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.9.0...version-bump-w_flux-2-9-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.9.0...2.9.1
> WP-4925 Release w_flux 2.9.1

- pubspec.yaml
- smithy.yaml
- tool/dev.dart
w_flux is ddc compliant, but future changes could lead to test failures with ddc 
Run tests with ddc in smithy!
@Workiva/web-platform-pp
> WP-4882 Add DDC Tests in CI

- lib/src/store.dart
The message associated with the `StateError` that is thrown when an action subscription is managed or when the store is listened to after disposal is cryptic.
Add the `runtimeType` to help the situation a bit.
None.
Existing tests are sufficient, the new error message is an ergonomic issue.
1. CI passes
@seanburke-wf
> WP-5043 Improve store state error messages

- pubspec.yaml
Widen react-dart dependency to include 4.0.0.
react-dart 4.0.0 includes improvements to Dart component instance management that help avoid certain memory leaks. See more info here: https://github.com/cleandart/react-dart/pull/127.
While this release contains breaking changes, those breakages are limited to internals that should be smoothed over by over_react, and should not affect the majority of consumers.
Widen react-dart version range to include 4.0.0.
Once this range has been widened throughout the Workiva's dependency tree, everyone should get 4.0.0 for free.
**Patch**
React component rendering/testing
> WP-5242 Widen react-dart range to include memory leak fix in 4.0.0

- pubspec.yaml
* [WP-5242 Widen react-dart range to include memory leak fix in 4.0.0](https://github.com/Workiva/w_flux/pull/111)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.9.3...Workiva:release_w_flux_2_9_4
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.9.3...2.9.4
> WP-5044 Release w_flux 2.9.4

- .travis.yml
- lib/src/component_common.dart
- test/component_test.dart
To implement tracing of Flux components in https://github.com/Workiva/app_intelligence_dart/pull/737, we needed a way to:
- know whether a call to `redraw` was triggered from a store handler, and know which store triggered the redraw
- set up a custom default handler for certain types of stores
- Add lifecycle methods to allow subclasses to safely hook into and override store redraw logic:
- `listenToStoreForRedraw`
- See example override [here](https://github.com/Workiva/app_intelligence_dart/blob/7714bd160f7d735b32a7e4beaa9e49bab8f2a6b9/lib/src/app_data_types/tracing/w_flux/traced_flux_component.dart#L150)
- `handleRedrawOn`
- See exampleoverride [here](https://github.com/Workiva/app_intelligence_dart/blob/7714bd160f7d735b32a7e4beaa9e49bab8f2a6b9/lib/src/app_data_types/tracing/w_flux/tra …
> AF-2888 Accommodate tracing of Store triggers and resulting redraws

- README.md
Fix http -> https for `http://codecov.io/github/Workiva/w_flux/coverage.svg?branch=master` link.
> Fix http -> https

- pubspec.yaml
* [CPLAT-3300: CP Code Review and PR Merging Team agreement update](https://github.com/Workiva/w_flux/pull/126)
* [Fix http -> https](https://github.com/Workiva/w_flux/pull/127)
* [CPLAT-6767 Bump build dep ranges to fix build in master](https://github.com/Workiva/w_flux/pull/129)
Requested by: @smaifullerton-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.6.0...Workiva:release_w_flux_2.10.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.6.0...2.10.2
> CPLAT-2948 Release w_flux 2.10.2

- lib/src/action.dart
- lib/src/store.dart
- pubspec.yaml
Some of the classes that extend or mixin `Disposable` missing `disposableTypeName` override.
This PR will add missing overrides, where it's necessary
> CPLAT-6850: Add disposable type name(s)

- example/random_color/random_color.dart
- example/todo_app/todo_app.dart
- pubspec.yaml
This release opens the upper-bound of the react dependency to allow 5.x releases.
> RM-55910 Release w_flux 2.10.4

- dart_test.yaml
- example/todo_app/components/new_todo_input.dart
- example/todo_app/components/todo_list_item.dart
- pubspec.yaml
- test/action_test.dart
- test/component_server_test.dart
- test/store_test.dart
> __These changes / builds will first be reviewed by a member of the Client Platform team.__
>
> Repo owners will be notified when it is ready for additional review, merge and release.
Now that React 16 is part of Production Wdesk we are coming back through to clean up the transitional comments, and dependency ranges.
We're also taking this opportunity to give you a head start on consuming Component2 / UiComponent2!
> __For more details, see [the Component2 Wiki](https://wiki.atl.workiva.net/display/CP/What%27s+new+in+Component2).__
To summarize Component2 changes:
- Supports new lifecycle methods, allowing us to use Concurrent Mode in the future
- Slightly faster
- Improved dev experience
- Props/state show up in the React DevTools, and primitive values (strings, numbers, booleans) can …
> CPLAT-8207: Cleanup React 16 Transition

- lib/src/mixins/batched_redraws.dart
_**Featuring @greglittlefield-wf as co-author!**_ 
While checking the performance of componentry in a consuming repo, it was noticed that occasionally batched updates would hold up the thread preventing anything else from executing. This becomes problematic for things like data fetching. If the batch redraw starts after a data request is sent the response cannot be handled until batch redraws finishes, and if these batched redraws take a lot of time (lots of components to update) it will push checking/handling the data fetching response until it finishes, Making data fetching artificially take longer.
- Add a tick between each redraw.
While we …
> Prevent BatchedRedraws from holding up the thread

- pubspec.yaml
Requested by: @joebingham-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.10.9...Workiva:release_w_flux_2.11.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.10.9...2.11.0
> Release w_flux 2.11.0

- Dockerfile
- example/README.md
This Sourcegraph batch replaces deprecated commands from the Dart SDK with the new ones.
All new CLI commands now live under the main `dart` executable. See this issue for the details
https://github.com/dart-lang/sdk/issues/46100
This PR might need to be checked or tweaked for possible errors in the arguments to 
`dart analyze` and `dart format` since they take slightly different arguments than the original.
In most cases for analyze all the arguments can be removed and it can just be `dart analyze`.
Some of the argument changes were difficult to match and replace in an automated way. Since
there are only a few places that might break, it'll be easier to let the batch create the PR
and then manually adjust them.
`-w` should be removed automatically since overwriting files is now the …
> Replace deprecated commands with new dart commands

- skynet.yaml
Currently release pipelines are failing because they require a skynet run in order to pass the testing phase of the pipeline. We would like to not have to manually check that the github workflow passed and override the pipeline so we need a way to automatically check that the workflow passed and tell the pipeline that all is good.
Add a skynet.yaml that checks the github workflow run and passes or fails the skynet run depending on the results.
Add skynet run to check that the github workflow run passes  
[contributing-review-types]: …
> FW-58 Add skynet run that checks that github workflow run passes

- pubspec.yaml
* [FW-58 Add skynet run that checks that github workflow run passes](https://github.com/Workiva/w_flux/pull/163)
* [Fix w_common v2 breaking changes](https://github.com/Workiva/w_flux/pull/165)
Requested by: @evanweible-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.10.20...Workiva:release_w_flux_2.10.21
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.10.20...2.10.21
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6058676244709376/?repo_name=Workiva%2 …
> RM-149237 Release w_flux 2.10.21

- pubspec.yaml
Summary
---
Frontend Frameworks is updating dependencies! More details at
https://wiki.atl.workiva.net/display/CP/Dependency+Upgrades
This update will allow w_common 2x by raising the max to < 3.0.0
It also raises the minimum of a few packages that addressed w_common
v2 breaking changes. In order to be compatible with w_common v2, we
need at least these versions.
dart_dev_workiva 1.5.9
wdesk_sdk 3.7.8
w_router 1.1.15
w_flux 2.10.21
w_module 2.0.30
bigsky_rest_files 1.33.10
In addition, sass compilation was moved out of w_common into a 
w_common_tools package, so if it detects that the repo might need it, 
it might add a dependency on w_common_tools.
Lastly, app/pubspec.lock files may have needed to be updated to get 
those minimum versions of packages
For more info, reach out to …
> w_common v2 rollout - 1 of 2 raise max

- pubspec.yaml
* [w_common v2 rollout - 2 of 2 raise min](https://github.com/Workiva/w_flux/pull/170)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.10.22...Workiva:release_w_flux_2.10.23
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.10.22...2.10.23
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6058676244709376/?repo_name=Workiva%2Fw_flux&pull_number=171)
> RM-162051 Release w_flux 2.10.23

- .github/workflows/dart_ci.yml
- Dockerfile
- dart_dependency_validator.yaml
- pubspec.yaml
Summary
---
This batch overrides the docker images used to equivalent Dart 2.18 versions.
The goal is to run as many CI runs across the dart ecosystem as possible on 
Dart 2.18 to find and fix errors before releasing a production 2.18 image.
For more info, reach out to `#support-frontend-dx` on Slack.
[_Created by Sourcegraph batch change `Workiva/test_dart_218`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/test_dart_218)
> Test Dart 2.18

- pubspec.yaml
* [Test Dart 2.18](https://github.com/Workiva/w_flux/pull/173)
* [Raise analyzer minimum & unpin meta](https://github.com/Workiva/w_flux/pull/174)
* [Prepare for dart_dev v4.0.0](https://github.com/Workiva/w_flux/pull/176)
* [w_common v3 rollout - 1 of 2 raise max](https://github.com/Workiva/w_flux/pull/177)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.10.23...Workiva:release_w_flux_2.10.24
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.10.23...2.10.24
This pull request can be recreated by …
> RM-163291 Release w_flux 2.10.24

- pubspec.yaml
* [Make example a separate pkg to remove over_react](https://github.com/Workiva/w_flux/pull/179)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.10.24...Workiva:release_w_flux_2.10.25
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.10.24...2.10.25
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6058676244709376/?repo_name=Workiva%2Fw_flux&pull_number=180)
> RM-188016 Release w_flux 2.10.25

- CHANGELOG.md
- lib/src/action.dart
- lib/src/store.dart
- test/action_test.dart
Adding APIs in major versions introduces risk, since consumers with opened ranges could accidentally consume new APIs. So instead of exposing Action2 in w_flux 3.0, we will backpatch Action2 to a w_flux 2.x minor, so that it won't be an API addition in w_flux 3.0. This option enables us to start work on the Action migration before the w_flux major release has finished rolling out
Add Action2 and appropriate test coverage without null safety work.
[contributing-review-types]: https://github.com/Workiva/w_flux/blob/master/CONTRIBUTING.md#review-types …
> FEA-2771 Add ActionV2 w/o null safety

- example/pubspec.yaml
- pubspec.yaml
This PR raises the max version of build_web_compilers to 5.0.0 to prep for Dart 3. 
Since we're all on Dart 2.19 right now, no pub resolution will change as we can't
actually resolve to build_web_compilers 4+ without Dart 3.
Passing CI should be sufficient for QA, so feel free to review and merge this once CI completes.
For more info, reach out to `$support-frontend-dx` on Slack.
[_Created by Sourcegraph batch change `Workiva/build_web_compilers_raise_max_v5_0_0`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/build_web_compilers_raise_max_v5_0_0)
> Raise the build_web_compilers dependency max to v5.0.0

- example/pubspec.yaml
- pubspec.yaml
For Dart packages that have migrated to null safety (full or partial)
we can raise the minimum Dart SDK version to 2.19.0 instead of 2.12.0.
This will allow us to take advantage of new language features as soon as
files are migrated to null safety. We've shown that unmigrated consumers
do not have issues consuming packages with a higher minimum Dart SDK version.
- Raise minimum Dart SDK version to 2.19.0
[_Created by Sourcegraph batch change `Workiva/raise_min_dart_sdk_2_19`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/raise_min_dart_sdk_2_19)
> raise_min_dart_sdk_2_19

- pubspec.yaml
* [FEA-2770 FEA-2772 Action v2 type migration](https://github.com/Workiva/w_flux/pull/195)
* [DSC-10119 - Complete transition to GHA](https://github.com/Workiva/w_flux/pull/198)
* [FEDX-1708: Workiva Analysis Options v2](https://github.com/Workiva/w_flux/pull/199)
* [Raise the build_web_compilers dependency max to v5.0.0](https://github.com/Workiva/w_flux/pull/200)
* [Raise the meta dependency min to v1.16.0](https://github.com/Workiva/w_flux/pull/201)
* [raise_min_dart_sdk_2_19](https://github.com/Workiva/w_flux/pull/202)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/3.0.0...Workiva:release_w_flux_3.0.1
Diff Between Last Tag and New Tag: …
> RM-223555 Release w_flux 3.0.1
