Workiva/w_flux

- lib/src/component.dart
- lib/src/store.dart
- lib/w_flux.dart
In preparation of OSS, we need to fill out the source documentation.
Docstrings added for..
- `FluxComponent`
- `Store`
- The main `w_flux` library
> **Docs only change.**
n/a
n/a
@jayudey-wf
> CP-942 Document FluxComponent and Store

- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-794
CP-818  - add docs and examples, w_flux  - https://github.com/Workiva/w_flux/pull/23
CP-846  - Add CHANGELOG, w_flux  - https://github.com/Workiva/w_flux/pull/26
CP-853  - Use dart_dev for tooling, w_flux  - https://github.com/Workiva/w_flux/pull/24
CP-855  - Add license, copy license to all src files, w_flux  - https://github.com/Workiva/w_flux/pull/25
CP-857  - Prepare pubspec.yaml for OSS  - https://github.com/Workiva/w_flux/pull/31
CP-854  - Fix image link in README, w_flux  - https://github.com/Workiva/w_flux/pull/30
CP-937  - Setup Travis CI and codecov.io reporting, w_flux  - https://github.com/Workiva/w_flux/pull/33
CP-942  - Document FluxComponent and Store  - …
> CP-794 Release w_flux 1.0.0

- README.md
Fixes #29 
**Docs:**
- Add pub, travis, codecov badges to README
- None
- Docs only change
> CP-956 Add badges to README. w_flux

- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-951
CP-956  - Add badges to README. w_flux  - https://github.com/Workiva/w_flux/pull/37
CP-1017  - Fix usage of expect-async in action tests.  - https://github.com/Workiva/w_flux/pull/38
CP-1055  - Allow react 0.8.0 in dependency range, w_flux  - https://github.com/Workiva/w_flux/pull/40
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/1.0.0...CP-951_release_1.0.1
> CP-951 Release w_flux 1.0.1

- CHANGELOG.md
Changelog is out of date
- CI passes
- Docs only change
> CP-1060 Update CHANGELOG.md, w_flux

- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-1056
CP-1060  - Update CHANGELOG.md, w_flux  - https://github.com/Workiva/w_flux/pull/42
CP-1152  - Add clearListeners method to Action  - https://github.com/Workiva/w_flux/pull/44
REF-278  - Add RedrawScheduler to wFlux  - https://github.com/Workiva/w_flux/pull/45
CP-1168  - fix strong mode analysis errors / warnings, w_flux  - https://github.com/Workiva/w_flux/pull/46
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/1.0.1...CP-1056_release_1.1.0
> CP-1056 Release w_flux 1.1.0

- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-1188
CP-1192  - Store: switch to a default ctor and a transformer ctor  - https://github.com/Workiva/w_flux/pull/49
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/1.1.0...CP-1188_release_2.0.0
> CP-1188 Release w_flux 2.0.0

- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-1193
CP-1226  - cleanup old tooling, w_flux  - https://github.com/Workiva/w_flux/pull/52
CP-1415  - Allow use of react-dart 0.9.0, w_flux  - https://github.com/Workiva/w_flux/pull/53
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.0.0...CP-1193_release_2.1.0
> CP-1193 Release w_flux 2.1.0

- lib/src/component_common.dart
- lib/src/store.dart
- test/component_server_test.dart
- test/component_test.dart
- tool/dev.dart
Allow w_flux to be compatible with strong mode
> CHART-1760 make w_flux compatible with strong mode

- pubspec.yaml
* [CP-2596 Store implements Disposable](https://github.com/Workiva/w_flux/pull/75)
* [CP-2944 Fix intermittent failures, add basic smithy.yaml, add sleep to Travis CI startup](https://github.com/Workiva/w_flux/pull/78)
Requested by: @charliekump-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.5.0...version-bump-w_flux-2-6-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.5.0...2.6.0
> CP-2631 Release w_flux 2.6.0

- docs.yml
We would like this readme in the dev portal
Added docs.yml
previous major version
@dustinlessard-wf @evanweible-wf @jayudey-wf @maxwellpeterson-wf @sebastianmalysa-wf @trentgrover-wf
@Workiva/devtools-pp
> WP-3660 : added docs.yml

- README.md
Add a note about `over_react`'s strongly-typed FluxUiComponent for consumers of that package.
@Workiva/web-platform-pp 
@Workiva/rich-app-platform-pp
> WP-4052 Add a note about over_react's FluxUiComponent

- pubspec.yaml
* [WP-4432 Add lints and close test controllers.](https://github.com/Workiva/w_flux/pull/90)
* [WP-4459 Ignore trigger when disposed or disposing](https://github.com/Workiva/w_flux/pull/92)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.7.1...version-bump-w_flux-2-7-2
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.7.1...2.7.2
> WP-4414 Release w_flux 2.7.2

- lib/src/component_common.dart
- pubspec.yaml
Problem
--------
`rate_limit` is not strong mode compliant.
Solution
--------
Remove the dependency.
Potential Regressions
--------
None, the dependency appears unused.
Tests
--------
No changes.
QA / +10
--------
> WP-4449 Remove rate limit dependency.

- pubspec.yaml
* [WP-4882 Add DDC Tests in CI](https://github.com/Workiva/w_flux/pull/99)
* [WP-5012 revert batchedRedraw optimization](https://github.com/Workiva/w_flux/pull/107)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.9.1...Workiva:release_w_flux_2_9_2
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.9.1...2.9.2
> WP-4953 Release w_flux 2.9.2

- pubspec.yaml
* [WP-5043 Improve store state error messages](https://github.com/Workiva/w_flux/pull/109)
Requested by: @todbachman-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.9.2...Workiva:release_w_flux_2_9_3
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.9.2...2.9.3
> WP-5013 Release w_flux 2.9.3

- pubspec.yaml
* [Fixes for dart 2 types all the way through](https://github.com/Workiva/w_flux/pull/113)
Requested by: @evanweible-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.9.4...Workiva:release_w_flux_2_9_5
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.9.4...2.9.5
> WP-5245 Release w_flux 2.9.5

- pubspec.yaml
* [BUILDTOOLS-2329: Update Dockerfile to mirror smithy.yaml](https://github.com/Workiva/w_flux/pull/115)
* [af_new_drydock_image](https://github.com/Workiva/w_flux/pull/116)
* [AF-2888 Accommodate tracing of Store triggers and resulting redraws](https://github.com/Workiva/w_flux/pull/120)
Requested by: @greglittlefield-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.9.5...Workiva:release_w_flux_2.10.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.9.5...2.10.0
> WP-6180 Release w_flux 2.10.0

- pubspec.yaml
* [AF-2938 dart2 fixes](https://github.com/Workiva/w_flux/pull/123)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.10.0...Workiva:release_w_flux_2.10.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.10.0...2.10.1
> AF-2930 Release w_flux 2.10.1

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Client Platform is refreshing our contributing instructions as a result of solidifying our internal CP Code Review
and PR Merging Team agreement.
You can view the Details in this RFD: https://docs.google.com/document/d/1zQ9gMMnQo3AyYQfCThCwB76aYpU3BMmqm1faD5EA8bU/edit
This PR aligns the CONTRIBUTING.md and PULL_REQUEST_TEMPLATE.md with the new agreement.
- Removes all existing potential variations of CONTRIBUTING, PULL_REQUEST_TEMPLATE, and CODEOWNERS.
- Adds standardized PULL_REQUEST_TEMPLATE.md and CONTRIBUTING.md
> AF-3300: CP Code Review and PR Merging Team agreement update

- .travis.yml
- Dockerfile
- pubspec.yaml
Building in master is currently erroring with: 
```
[SEVERE] build_web_compilers:ddc on package:package_resolver/package_resolver.dartdevc.module:
Error compiling dartdevc module:package_resolver|lib/package_resolver.ddc.js
[error] The imported library ''current_isolate_resolver_stub.dart'' can't have a part-of directive. (package:package_resolver/src/package_resolver.dart, line 12, col 8)
[error] The imported library ''utils_isolate_stub.dart'' can't have a part-of directive. (package:package_resolver/src/utils.dart, line 15, col 8)
Please fix all errors before compiling (warnings are okay).
```
Expand build_* dep range to get latest with fix.
Please review: …
> CPLAT-6767 Bump build dep ranges to fix build in master

- pubspec.yaml
* [CPLAT-6850: Add disposable type name(s)](https://github.com/Workiva/w_flux/pull/131)
Requested by: @olesiathoms-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.10.2...Workiva:release_w_flux_2.10.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.10.2...2.10.3
> RM-55459 Release w_flux 2.10.3

- lib/src/mixins/batched_redraws.dart
[contributing-review-types]: https://github.com/Workiva/w_flux/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/w_flux/blob/master/CONTRIBUTING.md#manual-testing-criteria
> Revert Batched Redraw Update

- lib/src/mixins/batched_redraws.dart
_**Featuring @greglittlefield-wf as co-author!**_ 
While checking the performance of componentry in a consuming repo, it was noticed that occasionally batched updates would hold up the thread preventing anything else from executing. This becomes problematic for things like data fetching. If the batch redraw starts after a data request is sent the response cannot be handled until batch redraws finishes, and if these batched redraws take a lot of time (lots of components to update) it will push checking/handling the data fetching response until it finishes, Making data fetching artificially take longer.
- Add a tick between each redraw.
While we …
> CPLAT-9165: Prevent BatchedRedraws from holding up the thread - take 2

- pubspec.yaml
Due to my own unawareness, master has the incorrect version number and does not match MARV. This re-aligns it, and should ultimately trigger the 2.10.10 release.
- Change version from 2.11.0 to 2.10.9
- Fix version discrepancy 
[contributing-review-types]: https://github.com/Workiva/w_flux/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/w_flux/blob/master/CONTRIBUTING.md#manual-testing-criteria
> Change version to match MARV

- .travis.yml
- pubspec.yaml
Newer versions of `over_react` use extension methods which are not compatible with Dart versions below 2.7.
- Update CI to run on `2.7.2`
[contributing-review-types]: https://github.com/Workiva/w_flux/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/w_flux/blob/master/CONTRIBUTING.md#manual-testing-criteria
> Update CI to run on 2.7.2

- pubspec.yaml
> __These changes / builds will first be reviewed by a member of the Client Platform team.__
>
> Repo owners will be notified when it is ready for additional review, merge and release.
React 17 was released at the end of October and came with some exciting benefits. For the full list, see the [ReactJS blog post](https://reactjs.org/blog/2020/10/20/react-v17.html).
For Workiva, upgrading so promptly is even more exciting because it:
1. supports our Material-UI (MUI) effort. [MUI will support React 17](https://github.com/mui-org/material-ui/blob/next/CHANGELOG.md#500-alpha15) in their next major release. This major is the one that Client Platform will use as the corner stone for the MUI effort. Therefore, to be compatible, Workiva should adopt React 17 as well.
1. helps with the …
> Preparations for React 17 compatibility

- pubspec.yaml
* [w_common v2 rollout - 1 of 2 raise max](https://github.com/Workiva/w_flux/pull/168)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.10.21...Workiva:release_w_flux_2.10.22
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.10.21...2.10.22
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6058676244709376/?repo_name=Workiva%2Fw_flux&pull_number=169)
> RM-159766 Release w_flux 2.10.22

- pubspec.yaml
* Minor changes:
* [FEA-2771 Add ActionV2 w/o null safety](https://github.com/Workiva/w_flux/pull/188)
* [Update dev dependencies for analyzer 2](https://github.com/Workiva/w_flux/pull/183)
* [Dart 2.19](https://github.com/Workiva/w_flux/pull/189)
Requested by: @sorenthompson-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.10.25...Workiva:release_w_flux_2.11.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.10.25...2.11.0
This pull request can be recreated by clicking …
> RM-191379 Release w_flux 2.11.0

- pubspec.yaml
* Major changes:
* [Null safety 3](https://github.com/Workiva/w_flux/pull/192)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.11.0...Workiva:release_w_flux_3.0.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.11.0...3.0.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6058676244709376/?repo_name=Workiva%2Fw_flux&pull_number=194)
> RM-222423 Release w_flux 3.0.0
